# Aim is to create a csv file containing image id and gender from imdb.mat file

In [1]:
import pandas as pd
import scipy.io

In [2]:
IMDB_DATASET_PATH = '../data/imdb_crop/'

In [3]:
imdb_mat_file = IMDB_DATASET_PATH + 'imdb.mat'
mat = scipy.io.loadmat(imdb_mat_file)

In [4]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Jan 17 11:30:27 2016',
 '__version__': '1.0',
 '__globals__': [],
 'imdb': array([[(array([[693726, 693726, 693726, ..., 726831, 726831, 726831]], dtype=int32), array([[1968, 1970, 1968, ..., 2011, 2011, 2011]], dtype=uint16), array([[array(['01/nm0000001_rm124825600_1899-5-10_1968.jpg'], dtype='<U43'),
         array(['01/nm0000001_rm3343756032_1899-5-10_1970.jpg'], dtype='<U44'),
         array(['01/nm0000001_rm577153792_1899-5-10_1968.jpg'], dtype='<U43'),
         ...,
         array(['08/nm3994408_rm926592512_1989-12-29_2011.jpg'], dtype='<U44'),
         array(['08/nm3994408_rm943369728_1989-12-29_2011.jpg'], dtype='<U44'),
         array(['08/nm3994408_rm976924160_1989-12-29_2011.jpg'], dtype='<U44')]],
       dtype=object), array([[1., 1., 1., ..., 0., 0., 0.]]), array([[array(['Fred Astaire'], dtype='<U12'),
         array(['Fred Astaire'], dtype='<U12'),
         array(['Fred Astaire'], dtype='<U12'), ...,
         array(['Jane Levy'], dtype='<U9'),
         array(['Jane Levy'], dtype='<U9'),
         array(['Jane Levy'], dtype='<U9')]], dtype=object), array([[array([[1072.926,  161.838, 1214.784,  303.696]]),
         array([[477.184, 100.352, 622.592, 245.76 ]]),
         array([[114.96964309, 114.96964309, 451.68657236, 451.68657236]]),
         ..., array([[  1,   1, 453, 640]], dtype=uint16),
         array([[144.75225472, 126.76472288, 305.78804127, 287.80050943]]),
         array([[457.524,  41.748, 518.016, 102.24 ]])]], dtype=object), array([[1.45969291, 2.5431976 , 3.45557949, ...,       -inf, 4.45072452,
         2.13350269]]), array([[1.11897336, 1.85200773, 2.98566022, ...,        nan,        nan,
                nan]]), array([[array(["'Lee' George Quinones"], dtype='<U21'),
         array(["'Weird Al' Yankovic"], dtype='<U19'),
         array(['2 Chainz'], dtype='<U8'), ...,
         array(['Éric Caravaca'], dtype='<U13'),
         array(['Ólafur Darri Ólafsson'], dtype='<U21'),
         array(['Óscar Jaenada'], dtype='<U13')]], dtype=object), array([[6488, 6488, 6488, ..., 8410, 8410, 8410]], dtype=uint16))]],
       dtype=[('dob', 'O'), ('photo_taken', 'O'), ('full_path', 'O'), ('gender', 'O'), ('name', 'O'), ('face_location', 'O'), ('face_score', 'O'), ('second_face_score', 'O'), ('celeb_names', 'O'), ('celeb_id', 'O')])}

In [5]:
mat['imdb']

array([[(array([[693726, 693726, 693726, ..., 726831, 726831, 726831]], dtype=int32), array([[1968, 1970, 1968, ..., 2011, 2011, 2011]], dtype=uint16), array([[array(['01/nm0000001_rm124825600_1899-5-10_1968.jpg'], dtype='<U43'),
        array(['01/nm0000001_rm3343756032_1899-5-10_1970.jpg'], dtype='<U44'),
        array(['01/nm0000001_rm577153792_1899-5-10_1968.jpg'], dtype='<U43'),
        ...,
        array(['08/nm3994408_rm926592512_1989-12-29_2011.jpg'], dtype='<U44'),
        array(['08/nm3994408_rm943369728_1989-12-29_2011.jpg'], dtype='<U44'),
        array(['08/nm3994408_rm976924160_1989-12-29_2011.jpg'], dtype='<U44')]],
      dtype=object), array([[1., 1., 1., ..., 0., 0., 0.]]), array([[array(['Fred Astaire'], dtype='<U12'),
        array(['Fred Astaire'], dtype='<U12'),
        array(['Fred Astaire'], dtype='<U12'), ...,
        array(['Jane Levy'], dtype='<U9'),
        array(['Jane Levy'], dtype='<U9'),
        array(['Jane Levy'], dtype='<U9')]], dtype=object), array([[array([[1072.926,  161.838, 1214.784,  303.696]]),
        array([[477.184, 100.352, 622.592, 245.76 ]]),
        array([[114.96964309, 114.96964309, 451.68657236, 451.68657236]]),
        ..., array([[  1,   1, 453, 640]], dtype=uint16),
        array([[144.75225472, 126.76472288, 305.78804127, 287.80050943]]),
        array([[457.524,  41.748, 518.016, 102.24 ]])]], dtype=object), array([[1.45969291, 2.5431976 , 3.45557949, ...,       -inf, 4.45072452,
        2.13350269]]), array([[1.11897336, 1.85200773, 2.98566022, ...,        nan,        nan,
               nan]]), array([[array(["'Lee' George Quinones"], dtype='<U21'),
        array(["'Weird Al' Yankovic"], dtype='<U19'),
        array(['2 Chainz'], dtype='<U8'), ...,
        array(['Éric Caravaca'], dtype='<U13'),
        array(['Ólafur Darri Ólafsson'], dtype='<U21'),
        array(['Óscar Jaenada'], dtype='<U13')]], dtype=object), array([[6488, 6488, 6488, ..., 8410, 8410, 8410]], dtype=uint16))]],
      dtype=[('dob', 'O'), ('photo_taken', 'O'), ('full_path', 'O'), ('gender', 'O'), ('name', 'O'), ('face_location', 'O'), ('face_score', 'O'), ('second_face_score', 'O'), ('celeb_names', 'O'), ('celeb_id', 'O')])

In [6]:
imdb_mat = mat['imdb']

In [7]:
imdb_mat.dtype

dtype([('dob', 'O'), ('photo_taken', 'O'), ('full_path', 'O'), ('gender', 'O'), ('name', 'O'), ('face_location', 'O'), ('face_score', 'O'), ('second_face_score', 'O'), ('celeb_names', 'O'), ('celeb_id', 'O')])

In [8]:
image_paths = imdb_mat['full_path'][0,0][0]
image_paths

array([array(['01/nm0000001_rm124825600_1899-5-10_1968.jpg'], dtype='<U43'),
       array(['01/nm0000001_rm3343756032_1899-5-10_1970.jpg'], dtype='<U44'),
       array(['01/nm0000001_rm577153792_1899-5-10_1968.jpg'], dtype='<U43'),
       ...,
       array(['08/nm3994408_rm926592512_1989-12-29_2011.jpg'], dtype='<U44'),
       array(['08/nm3994408_rm943369728_1989-12-29_2011.jpg'], dtype='<U44'),
       array(['08/nm3994408_rm976924160_1989-12-29_2011.jpg'], dtype='<U44')],
      dtype=object)

In [9]:
image_list = []
for image in image_paths:
    image_list.append(image[0])

In [10]:
genders = imdb_mat['gender'][0,0][0]
genders

array([1., 1., 1., ..., 0., 0., 0.])

In [11]:
gender_list = []
for gender in genders:
    gender_list.append(gender)

In [12]:
gender_df = pd.DataFrame({'image_path': image_list, 'gender': gender_list})

In [13]:
gender_df

                                           image_path  gender
0         01/nm0000001_rm124825600_1899-5-10_1968.jpg     1.0
1        01/nm0000001_rm3343756032_1899-5-10_1970.jpg     1.0
2         01/nm0000001_rm577153792_1899-5-10_1968.jpg     1.0
3         01/nm0000001_rm946909184_1899-5-10_1968.jpg     1.0
4         01/nm0000001_rm980463616_1899-5-10_1968.jpg     1.0
5        02/nm0000002_rm1075631616_1924-9-16_1991.jpg     0.0
6        02/nm0000002_rm1346607872_1924-9-16_2004.jpg     0.0
7        02/nm0000002_rm1363385088_1924-9-16_2004.jpg     0.0
8        02/nm0000002_rm1411175936_1924-9-16_1991.jpg     0.0
9        02/nm0000002_rm1447271168_1924-9-16_2004.jpg     0.0
10       02/nm0000002_rm1624085760_1924-9-16_2008.jpg     0.0
11       02/nm0000002_rm1646056960_1924-9-16_1991.jpg     0.0
12        02/nm0000002_rm221957120_1924-9-16_1974.jpg     0.0
13       02/nm0000002_rm2287049216_1924-9-16_2007.jpg     0.0
14        02/nm0000002_rm238734336_1924-9-16_1974.jpg     0.0
15       02/nm0000002_rm2585828096_1924-9-16_2006.jpg     0.0
16       02/nm0000002_rm2602605312_1924-9-16_2006.jpg     0.0
17       02/nm0000002_rm2619382528_1924-9-16_2006.jpg     0.0
18       02/nm0000002_rm2769394176_1924-9-16_2006.jpg     0.0
19       02/nm0000002_rm2780403712_1924-9-16_2004.jpg     0.0
20       02/nm0000002_rm2805435904_1924-9-16_1988.jpg     0.0
21       02/nm0000002_rm2813958144_1924-9-16_2004.jpg     0.0
22        02/nm0000002_rm289065984_1924-9-16_1974.jpg     0.0
23       02/nm0000002_rm2983566080_1924-9-16_2007.jpg     0.0
24        02/nm0000002_rm305843200_1924-9-16_1974.jpg     0.0
25       02/nm0000002_rm3224279040_1924-9-16_2005.jpg     0.0
26       02/nm0000002_rm3453524224_1924-9-16_2007.jpg     0.0
27       02/nm0000002_rm3487078656_1924-9-16_2007.jpg     0.0
28        02/nm0000002_rm350394368_1924-9-16_2005.jpg     0.0
29       02/nm0000002_rm3537671424_1924-9-16_2008.jpg     0.0
...                                               ...     ...
460693   08/nm3994408_rm350134272_1989-12-29_2013.jpg     0.0
460694  08/nm3994408_rm3532828160_1989-12-29_2012.jpg     0.0
460695   08/nm3994408_rm357150464_1989-12-29_2011.jpg     0.0
460696  08/nm3994408_rm3650268672_1989-12-29_2012.jpg     0.0
460697  08/nm3994408_rm3713712128_1989-12-29_2014.jpg     0.0
460698     08/nm3994408_rm3845632_1989-12-29_2011.jpg     0.0
460699  08/nm3994408_rm3926507520_1989-12-29_2014.jpg     0.0
460700  08/nm3994408_rm4062552064_1989-12-29_2011.jpg     0.0
460701  08/nm3994408_rm4163215360_1989-12-29_2011.jpg     0.0
460702  08/nm3994408_rm4179992576_1989-12-29_2011.jpg     0.0
460703   08/nm3994408_rm474590976_1989-12-29_2011.jpg     0.0
460704   08/nm3994408_rm524922624_1989-12-29_2011.jpg     0.0
460705   08/nm3994408_rm540716544_1989-12-29_2011.jpg     0.0
460706     08/nm3994408_rm5419776_1989-12-29_2011.jpg     0.0
460707   08/nm3994408_rm543141888_1989-12-29_2011.jpg     0.0
460708   08/nm3994408_rm559919104_1989-12-29_2011.jpg     0.0
460709    08/nm3994408_rm56609536_1989-12-29_2011.jpg     0.0
460710   08/nm3994408_rm591048192_1989-12-29_2011.jpg     0.0
460711   08/nm3994408_rm605006080_1989-12-29_2012.jpg     0.0
460712   08/nm3994408_rm663989760_1989-12-29_2012.jpg     0.0
460713   08/nm3994408_rm674934272_1989-12-29_2011.jpg     0.0
460714   08/nm3994408_rm727691264_1989-12-29_2011.jpg     0.0
460715    08/nm3994408_rm73386752_1989-12-29_2011.jpg     0.0
460716   08/nm3994408_rm744468480_1989-12-29_2011.jpg     0.0
460717   08/nm3994408_rm758820352_1989-12-29_2011.jpg     0.0
460718   08/nm3994408_rm761245696_1989-12-29_2011.jpg     0.0
460719   08/nm3994408_rm784182528_1989-12-29_2011.jpg     0.0
460720   08/nm3994408_rm926592512_1989-12-29_2011.jpg     0.0
460721   08/nm3994408_rm943369728_1989-12-29_2011.jpg     0.0
460722   08/nm3994408_rm976924160_1989-12-29_2011.jpg     0.0

[460723 rows x 2 columns]

In [14]:
csv_path = IMDB_DATASET_PATH + 'gender_df.csv'
gender_df.to_csv(csv_path,index=False)